Update PR-test.yaml

diff --git a/.github/workflows/PR-test.yaml b/.github/workflows/PR-test.yaml
--- a/.github/workflows/PR-test.yaml
+++ b/.github/workflows/PR-test.yaml
@@ -33,6 +33,10 @@ jobs:
           npm run feature-test
 
     # Step 5: Block PR if tests fail (Exit code is non-zero)
-      - name: Block PR if tests fail
-        if: ${{ failure() }}
-        run: exit 1
+  block-pr-if-failed:
+      runs-on: ubuntu-latest
+      needs: test  # This job runs after the 'test' job
+      if: ${{ failure() }}  # Only run this job if the 'test' job has failed
+      steps:
+        - name: Block PR if tests fail
+          run: exit 1  # This forces the PR to fail if the tests fail
